### ISSUE TITLE
poetry scripts break when building with --with-top-namespace

### ISSUE THREAD

**Issue by randomgeek78** [DavidVujic/python-polylith#178]
**Describe the bug**
When building a wheel `build-project` together with the `--with-top-namespace` argument, all the package includes in all the components/packages are modified so they are namespaced with name of the `top-namespace` argument. But the console scripts are not modified.

This breaks the scripts. In order to not break the scripts, they need to be set to whatever the `top-namespace` argument will be in advance, thus limiting the utility of dynamically modifying the namespace during build.

**To Reproduce**
Consider the following pyproject.toml
```toml
[tool.poetry]
name = "qaccess"
version = "0.0.0"

packages = [
    {include = "my_package", from = "src"},
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test_entrypoint = "my_package:main"
```

When I build this project w/ `poetry build-project --with-top-namespace=xyz`, I get a wheel. All the libraries except for the console script are now under the xyz namespace. 

When the wheel is unzipped, we have-
```
$ cat qaccess-0.0.0.dist-info/entry_points.txt 
[console_scripts]
test_entrypoint=my_package:main
```

When the wheel is installed and the `test_entrypoint` is called, it gives-

```
File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:992, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1004, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'my_package'
```
This happens because `my_package` is not inside the `xyz` namespace.
