### ISSUE TITLE
[Feature] Optionally generate `py.typed` stub file, while creating bases & components

### ISSUE THREAD

**Issue by joe733** [DavidVujic/python-polylith#94]
**Is your feature request related to a problem? Please describe.**

Pyright (strict) keeps complaining of missing typing stub file.

**Describe the solution you'd like**

`poetry poly create ...` can generate an empty `py.typed` stub file along side `__init__.py` and `core.py`.

**Describe alternatives you've considered**

This could be poly's default behaviour or invoked by a CLI option.

**Comment by DavidVujic** [comment]
Hi @joe733, thank you for reporting this issue!

If I recall this correctly, I think I initially had this issue with MyPy too. But solved it with a configuration. For MyPy, it would be:

```toml
mypy_path = components, bases
namespace_packages = True
explicit_package_bases = True
```

Could that be a solution (if something similar can be configured for Pyright)?
